name: PR Test Build

on:
  push:
    branches: [ci-test]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name to build"
        required: true
        default: "main"
defaults:
  run:
    shell: bash
jobs:
  PR_test_build:
    runs-on: linux-amd64
    container:
      image: ghcr.io/mrcyjanek/cake_wallet:main
      env:
        STORE_PASS: test@cake_wallet
        KEY_PASS: test@cake_wallet
        PR_NUMBER: 1234
        MONEROC_CACHE_DIR_ROOT: /opt/generic_cache
        BRANCH_NAME: main
      volumes:
        - /opt/cw_cache_android/root/.cache:/root/.cache
        - /opt/cw_cache_android/root/.pub-cache/:/root/.pub-cache
        - /opt/cw_cache_android/root/.gradle/:/root/.gradle
        - /opt/cw_cache_android/root/.android/:/root/.android
        - /opt/cw_cache_android/root/go/pkg:/root/go/pkg
        - /opt/cw_cache_android/opt/generic_cache:/opt/generic_cache
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: is pr
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> /etc/environment

      - name: is not pr
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> /etc/environment
      - uses: actions/checkout@v4
      - name: configure git
        run: |
          git config --global user.email "czarek@cakewallet.com"
          git config --global user.name "CakeWallet CI"
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: false
      - name: prepare monero_c and cache
        run: |
          export MONEROC_HASH=$(cat scripts/prepare_moneroc.sh | grep 'git checkout' | xargs | awk '{ print $3 }')
          echo MONEROC_HASH=$MONEROC_HASH >> /etc/environment
          mkdir -p "$MONEROC_CACHE_DIR_ROOT/$MONEROC_HASH/monero_c"
          pushd scripts
            ln -s "$MONEROC_CACHE_DIR_ROOT/$MONEROC_HASH/monero_c"
            ./prepare_moneroc.sh
          popd

      - name: Generate KeyStore
        run: |
          pushd /opt/generic_cache
            if [[ ! -f key.jks ]];
            then
              keytool -genkey -v -keystore key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias testKey -noprompt -dname "CN=CakeWallet, OU=CakeWallet, O=CakeWallet, L=Florida, S=America, C=USA" -storepass $STORE_PASS -keypass $KEY_PASS
            else
              echo "$PWD/key.jks exist, not generating"
            fi
          popd
          cp /opt/generic_cache/key.jks android/app

      - name: Execute Build and Setup Commands
        run: |
          pushd scripts/android
            source ./app_env.sh cakewallet
            ./app_config.sh
          popd

      - name: Build monero_c
        run: |
          pushd scripts/android/
            source ./app_env.sh cakewallet
            ./build_monero_all.sh
          popd

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Build mwebd
        run: |
          pushd scripts/android
            gomobile init
            ./build_mwebd.sh --dont-install
          popd

      - name: Build generated code
        run: |
          ./model_generator.sh async

      - name: Generate key properties
        run: |
          dart run tool/generate_android_key_properties.dart keyAlias=testKey storeFile=key.jks storePassword=$STORE_PASS keyPassword=$KEY_PASS

      - name: Generate localization
        run: |
          dart run tool/generate_localization.dart

      - name: Add secrets
        run: |
          touch lib/.secrets.g.dart
          touch cw_evm/lib/.secrets.g.dart
          touch cw_solana/lib/.secrets.g.dart
          touch cw_core/lib/.secrets.g.dart
          touch cw_nano/lib/.secrets.g.dart
          touch cw_tron/lib/.secrets.g.dart
          if [[ "x${{ secrets.SALT }}" == "x" ]];
          then
            echo "const salt = '954f787f12622067f7e548d9450c3832';" > lib/.secrets.g.dart
          else
            echo "const salt = '${{ secrets.SALT }}';" > lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.KEY_CHAIN_SALT }}" == "x" ]];
          then
            echo "const keychainSalt = '2d2beba777dbf7dff7013b7a';" >> lib/.secrets.g.dart
          else
            echo "const keychainSalt = '${{ secrets.KEY_CHAIN_SALT }}';" >> lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.KEY }}" == "x" ]];
          then
            echo "const key = '638e98820ec10a2945e968435c9397a3';" >> lib/.secrets.g.dart
          else
            echo "const key = '${{ secrets.KEY }}';" >> lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.WALLET_SALT }}" == "x" ]];
          then
            echo "const walletSalt = '8f7f1b70';" >> lib/.secrets.g.dart
          else
            echo "const walletSalt = '${{ secrets.WALLET_SALT }}';" >> lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.SHORT_KEY }}" == "x" ]];
          then
            echo "const shortKey = '653f270c2c152bc7ec864afe';" >> lib/.secrets.g.dart
          else
            echo "const shortKey = '${{ secrets.SHORT_KEY }}';" >> lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.BACKUP_SALT }}" == "x" ]];
          then
            echo "const backupSalt = 'bf630d24ff0b6f60';" >> lib/.secrets.g.dart
          else
            echo "const backupSalt = '${{ secrets.BACKUP_SALT }}';" >> lib/.secrets.g.dart
          fi
          if [[ "x${{ secrets.BACKUP_KEY_CHAIN_SALT }}" == "x" ]];
          then
            echo "const backupKeychainSalt = 'bf630d24ff0b6f60';" >> lib/.secrets.g.dart
          else
            echo "const backupKeychainSalt = '${{ secrets.BACKUP_KEY_CHAIN_SALT }}';" >> lib/.secrets.g.dart
          fi
          echo "const changeNowApiKey = '${{ secrets.CHANGE_NOW_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const changeNowApiKeyDesktop = '${{ secrets.CHANGE_NOW_API_KEY_DESKTOP }}';" >> lib/.secrets.g.dart
          echo "const wyreSecretKey = '${{ secrets.WYRE_SECRET_KEY }}';" >> lib/.secrets.g.dart
          echo "const wyreApiKey = '${{ secrets.WYRE_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const wyreAccountId = '${{ secrets.WYRE_ACCOUNT_ID }}';" >> lib/.secrets.g.dart
          echo "const moonPayApiKey = '${{ secrets.MOON_PAY_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const moonPaySecretKey = '${{ secrets.MOON_PAY_SECRET_KEY }}';" >> lib/.secrets.g.dart
          echo "const sideShiftAffiliateId = '${{ secrets.SIDE_SHIFT_AFFILIATE_ID }}';" >> lib/.secrets.g.dart
          echo "const simpleSwapApiKey = '${{ secrets.SIMPLE_SWAP_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const simpleSwapApiKeyDesktop = '${{ secrets.SIMPLE_SWAP_API_KEY_DESKTOP }}';" >> lib/.secrets.g.dart
          echo "const onramperApiKey = '${{ secrets.ONRAMPER_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const anypayToken = '${{ secrets.ANY_PAY_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const ioniaClientId = '${{ secrets.IONIA_CLIENT_ID }}';" >> lib/.secrets.g.dart
          echo "const twitterBearerToken = '${{ secrets.TWITTER_BEARER_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const trocadorApiKey = '${{ secrets.TROCADOR_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const trocadorExchangeMarkup = '${{ secrets.TROCADOR_EXCHANGE_MARKUP }}';" >> lib/.secrets.g.dart
          echo "const anonPayReferralCode = '${{ secrets.ANON_PAY_REFERRAL_CODE }}';" >> lib/.secrets.g.dart
          echo "const fiatApiKey = '${{ secrets.FIAT_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const ankrApiKey = '${{ secrets.ANKR_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const chainStackApiKey = '${{ secrets.CHAIN_STACK_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const etherScanApiKey = '${{ secrets.ETHER_SCAN_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const polygonScanApiKey = '${{ secrets.POLYGON_SCAN_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const etherScanApiKey = '${{ secrets.ETHER_SCAN_API_KEY }}';" >> cw_evm/lib/.secrets.g.dart
          echo "const moralisApiKey = '${{ secrets.MORALIS_API_KEY }}';" >> cw_evm/lib/.secrets.g.dart
          echo "const nowNodesApiKey = '${{ secrets.EVM_NOWNODES_API_KEY }}';" >> cw_evm/lib/.secrets.g.dart
          echo "const chatwootWebsiteToken = '${{ secrets.CHATWOOT_WEBSITE_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const exolixApiKey = '${{ secrets.EXOLIX_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const robinhoodApplicationId = '${{ secrets.ROBINHOOD_APPLICATION_ID }}';" >> lib/.secrets.g.dart
          echo "const exchangeHelperApiKey = '${{ secrets.ROBINHOOD_CID_CLIENT_SECRET }}';" >> lib/.secrets.g.dart
          echo "const walletConnectProjectId = '${{ secrets.WALLET_CONNECT_PROJECT_ID }}';" >> lib/.secrets.g.dart
          echo "const moralisApiKey = '${{ secrets.MORALIS_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const polygonScanApiKey = '${{ secrets.POLYGON_SCAN_API_KEY }}';" >> cw_evm/lib/.secrets.g.dart
          echo "const ankrApiKey = '${{ secrets.ANKR_API_KEY }}';" >> cw_solana/lib/.secrets.g.dart
          echo "const chainStackApiKey = '${{ secrets.CHAIN_STACK_API_KEY }}';" >> cw_solana/lib/.secrets.g.dart
          echo "const testCakePayApiKey = '${{ secrets.TEST_CAKE_PAY_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const cakePayApiKey = '${{ secrets.CAKE_PAY_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const authorization = '${{ secrets.CAKE_PAY_AUTHORIZATION }}';" >> lib/.secrets.g.dart
          echo "const CSRFToken = '${{ secrets.CSRF_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const quantexExchangeMarkup = '${{ secrets.QUANTEX_EXCHANGE_MARKUP }}';" >> lib/.secrets.g.dart
          echo "const nano2ApiKey = '${{ secrets.NANO2_API_KEY }}';" >> cw_nano/lib/.secrets.g.dart
          echo "const nanoNowNodesApiKey = '${{ secrets.NANO_NOW_NODES_API_KEY }}';" >> cw_nano/lib/.secrets.g.dart
          echo "const tronGridApiKey = '${{ secrets.TRON_GRID_API_KEY }}';" >> cw_tron/lib/.secrets.g.dart
          echo "const tronNowNodesApiKey = '${{ secrets.TRON_NOW_NODES_API_KEY }}';" >> cw_tron/lib/.secrets.g.dart
          echo "const meldTestApiKey = '${{ secrets.MELD_TEST_API_KEY }}';" >> lib/.secrets.g.dart
          echo "const meldTestPublicKey = '${{ secrets.MELD_TEST_PUBLIC_KEY}}';" >> lib/.secrets.g.dart
          echo "const letsExchangeBearerToken = '${{ secrets.LETS_EXCHANGE_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const letsExchangeAffiliateId = '${{ secrets.LETS_EXCHANGE_AFFILIATE_ID }}';" >> lib/.secrets.g.dart
          echo "const stealthExBearerToken = '${{ secrets.STEALTH_EX_BEARER_TOKEN }}';" >> lib/.secrets.g.dart
          echo "const stealthExAdditionalFeePercent = '${{ secrets.STEALTH_EX_ADDITIONAL_FEE_PERCENT }}';" >> lib/.secrets.g.dart

      - name: Rename app
        run: |
          echo -e "id=com.cakewallet.test_$PR_NUMBER\nname=$BRANCH_NAME" > android/app.properties

      # Step 3: Download previous build number
      - name: Download previous build number
        id: download-build-number
        run: |
          # Download the artifact if it exists
          if [[ ! -f build_number.txt ]]; then
            echo "1" > build_number.txt
          fi

      # Step 4: Read and Increment Build Number
      - name: Increment Build Number
        id: increment-build-number
        run: |
          # Read current build number from file
          BUILD_NUMBER=$(cat build_number.txt)
          BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo "New build number: $BUILD_NUMBER"

          # Save the incremented build number
          echo "$BUILD_NUMBER" > build_number.txt

          # Export the build number to use in later steps
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      # Step 5: Update pubspec.yaml with new build number
      - name: Update build number
        run: |
          cd /opt/android/cake_wallet
          sed -i "s/^version: .*/version: 1.0.$BUILD_NUMBER/" pubspec.yaml

      - name: Build
        run: |
          cd /opt/android/cake_wallet
          flutter build apk --release --split-per-abi

      - name: Rename apk file
        run: |
          cd /opt/android/cake_wallet/build/app/outputs/flutter-apk
          mkdir test-apk
          cp app-arm64-v8a-release.apk test-apk/$BRANCH_NAME.apk
          cp app-x86_64-release.apk test-apk/${BRANCH_NAME}_x86.apk

      - name: Upload Artifact
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: /opt/android/cake_wallet/build/app/outputs/flutter-apk/test-apk/

      # Re-upload updated build number for the next run
      - name: Upload updated build number
        uses: actions/upload-artifact@v3
        with:
          name: build_number
          path: build_number.txt

      - name: Send Test APK
        continue-on-error: true
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: ${{ secrets.SLACK_APP_TOKEN }}
          path: /opt/android/cake_wallet/build/app/outputs/flutter-apk/test-apk/$BRANCH_NAME.apk
          channel: ${{ secrets.SLACK_APK_CHANNEL }}
          title: "$BRANCH_NAME.apk"
          filename: $BRANCH_NAME.apk
          initial_comment: ${{ github.event.head_commit.message }}

