name: Cake Wallet Android

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
